In [1]:
import numpy as np
from numpy import linalg

##### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
n = int(input())
np.arange(n-1, -1, -1)

10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [3]:
n = int(input())
np.flip(np.arange(n))

10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

##### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [4]:
n = int(input())
a = np.flip(np.arange(n))
np.diag(a)

10


array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
a_diag = np.diag(a)

In [6]:
sum(np.diagonal(a_diag))

45

##### Задание 3
Решите систему уравнений:<br>
4x + 2y + z = 4<br>
x + 3y = 12<br>
5y + 4z = -3<br>

In [7]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

In [8]:
linalg.solve(a,b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [9]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

##### Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [10]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [11]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [12]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [13]:
# создание словаря, в котором ключами будут id пользователей,
# а значениями — косинусы угла между векторами каждого пользователя и нового пользователя
cosines_dict = {i: cosine(j, next_user_stats) for i, j in enumerate(users_stats, 1)}
cosines_dict

{1: 0.19999999999999996,
 2: 0.8451542547285165,
 3: 0.3999999999999999,
 4: 0.7905694150420948,
 5: 0.3999999999999999,
 6: 0.0,
 7: 0.0,
 8: 0.9486832980505138,
 9: 0.0,
 10: 0.0}

In [14]:
# вывод id наиболее похожего пользователя
most_sim_user = max(cosines_dict, key=lambda k: cosines_dict[k])
most_sim_user

8