In [1]:
import numpy as np
import sympy as sym

## Уровень 0:

Представим фильмы в виде бинарных векторов (numpy array) используя следующие признаки:

[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

Игра в имитацию

Ярость

12 лет рабства

Однажды в Голливуде

In [2]:
film_1 = np.array([0,0,0,0,1,0])      # Игра в имитацию
film_2 = np.array([0,1,0,1,0,0])      # Ярость
film_3 = np.array([0,0,1,1,1,0])      # 12 лет рабства
film_4 = np.array([1,0,0,1,0,1])      # Однажды в Голливуде

### Задание 1

Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.

In [3]:
scalar_product = np.dot(film_2, film_3)

In [4]:
length_film_2 = np.linalg.norm(film_2)
length_film_3 = np.linalg.norm(film_3)

In [5]:
vector_multip = length_film_2 * length_film_3

In [6]:
cosine = scalar_product / vector_multip

In [7]:
angle = np.arccos(cosine)

In [8]:
angle_degrees = np.degrees(angle)

In [9]:
print(f'Угол между векторами:', angle_degrees)

Угол между векторами: 65.90515744788931


### Задание 2

Вычислить с помощью Python значение первой производной для функции $8x(x+3)^2$ в точке $x=1$

In [10]:
x = sym.Symbol('x')

In [11]:
func = 8*x*(x+3)**2
func

8*x*(x + 3)**2

In [12]:
diff = sym.diff(func, x)
diff

8*x*(2*x + 6) + 8*(x + 3)**2

In [13]:
value = diff.subs(x, 1)
value

192

### Задание 3

Объединить векторы фильмов в матрицу, где каждый вектор является строкой матрицы. Умножьте вектор [1,2,3,4] на полученную матрицу

In [14]:
film_matrix = np.array([
    film_1,
    film_2,
    film_3,
    film_4
])

film_matrix

array([[0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1]])

In [15]:
vector = np.array([1,2,3,4])
vector

array([1, 2, 3, 4])

In [16]:
np.matmul(vector, film_matrix)

array([4, 2, 3, 9, 4, 4])