In [1]:
import numpy as np

# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [2]:
matrix = np.arange(1, 10).reshape((3, 3))
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
diagonal_matrix = np.eye(3)
diagonal_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
result_matrix = matrix + diagonal_matrix
result_matrix

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [5]:
transposed_matrix = np.transpose(result_matrix)
transposed_matrix

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [6]:
inv_matrix = np.linalg.inv(result_matrix)
inv_matrix

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01,  2.22044605e-17],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [7]:
m = np.array([[2, 2],
              [1, 3]])
m

array([[2, 2],
       [1, 3]])

Собственные значения:

In [8]:
np.linalg.eigvals(m)

array([1., 4.])

Собственные вектора:

In [9]:
np.linalg.eig(m)[1]

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [10]:
det = 0
matrix = 0

while det != 1:
    matrix = np.random.randint(1, 10, size=(3,3))
    det = np.linalg.det(matrix)

Полученная матрица, соответствующая условиям:

In [11]:
print(matrix)
print(np.linalg.det(matrix))

[[1 1 1]
 [6 8 7]
 [6 9 8]]
1.0
